export const Currency = {
  AFN: "AFN",
  DZD: "DZD",
  ARS: "ARS",
  AWG: "AWG",
  AUD: "AUD",
  AZM: "AZM",
  BSD: "BSD",
  BHD: "BHD",
  THB: "THB",
  PAB: "PAB",
  BBD: "BBD",
  BYR: "BYR",
  BZD: "BZD",
  BMD: "BMD",
  VEB: "VEB",
  BOB: "BOB",
  BGN: "BGN",
  BRL: "BRL",
  BND: "BND",
  BIF: "BIF",
  CAD: "CAD",
  CVE: "CVE",
  KYD: "KYD",
  GHC: "GHC",
  XAF: "XAF",
  XPF: "XPF",
  CLP: "CLP",
  COP: "COP",
  KMF: "KMF",
  NIO: "NIO",
  CRC: "CRC",
  CUP: "CUP",
  CYP: "CYP",
  CZK: "CZK",
  DKK: "DKK",
  GMD: "GMD",
  MKD: "MKD",
  AED: "AED",
  DJF: "DJF",
  STD: "STD",
  DOP: "DOP",
  VND: "VND",
  AMD: "AMD",
  XCD: "XCD",
  EGP: "EGP",
  SVC: "SVC",
  ETB: "ETB",
  EUR: "EUR",
  FKP: "FKP",
  FJD: "FJD",
  HUF: "HUF",
  CDF: "CDF",
  GIP: "GIP",
  XAU: "XAU",
  HTG: "HTG",
  PYG: "PYG",
  GNF: "GNF",
  GYD: "GYD",
  HKD: "HKD",
  UAH: "UAH",
  ISK: "ISK",
  INR: "INR",
  IQD: "IQD",
  IRR: "IRR",
  JMD: "JMD",
  JOD: "JOD",
  KES: "KES",
  PGK: "PGK",
  LAK: "LAK",
  EEK: "EEK",
  HRK: "HRK",
  KWD: "KWD",
  MWK: "MWK",
  AOA: "AOA",
  MMK: "MMK",
  GEL: "GEL",
  LVL: "LVL",
  LBP: "LBP",
  ALL: "ALL",
  HNL: "HNL",
  SLL: "SLL",
  ROL: "ROL",
  LRD: "LRD",
  LYD: "LYD",
  SZL: "SZL",
  LTL: "LTL",
  LSL: "LSL",
  MGF: "MGF",
  MYR: "MYR",
  MTL: "MTL",
  TMM: "TMM",
  MUR: "MUR",
  MZM: "MZM",
  MXN: "MXN",
  MDL: "MDL",
  MAD: "MAD",
  NGN: "NGN",
  ERN: "ERN",
  NAD: "NAD",
  NPR: "NPR",
  ANG: "ANG",
  YUM: "YUM",
  ILS: "ILS",
  TWD: "TWD",
  NZD: "NZD",
  KPW: "KPW",
  NOK: "NOK",
  BTN: "BTN",
  PEN: "PEN",
  MRO: "MRO",
  TOP: "TOP",
  PKR: "PKR",
  XPD: "XPD",
  MOP: "MOP",
  UYU: "UYU",
  PHP: "PHP",
  XPT: "XPT",
  GBP: "GBP",
  BWP: "BWP",
  QAR: "QAR",
  GTQ: "GTQ",
  ZAR: "ZAR",
  OMR: "OMR",
  KHR: "KHR",
  MVR: "MVR",
  RON: "RON",
  IDR: "IDR",
  RUB: "RUB",
  RWF: "RWF",
  SAR: "SAR",
  XDR: "XDR",
  SCR: "SCR",
  XAG: "XAG",
  SGD: "SGD",
  SKK: "SKK",
  SBD: "SBD",
  SOS: "SOS",
  LKR: "LKR",
  KGS: "KGS",
  TJS: "TJS",
  SHP: "SHP",
  SDD: "SDD",
  SRG: "SRG",
  SEK: "SEK",
  CHF: "CHF",
  SYP: "SYP",
  BDT: "BDT",
  WST: "WST",
  TZS: "TZS",
  KZT: "KZT",
  SIT: "SIT",
  TTD: "TTD",
  MNT: "MNT",
  TND: "TND",
  TRY: "TRY",
  UGX: "UGX",
  USD: "USD",
  UZS: "UZS",
  VUV: "VUV",
  KRW: "KRW",
  YER: "YER",
  JPY: "JPY",
  CNY: "CNY",
  ZWD: "ZWD",
  PLN: "PLN",
} as const;

export type Currency = (typeof Currency)[keyof typeof Currency];

const aliases: Record<Currency, string> = {
  [Currency.AFN]: "Afghani",
  [Currency.DZD]: "Algerian Dinar",
  [Currency.ARS]: "Argentine Peso",
  [Currency.AWG]: "Aruban Guilder",
  [Currency.AUD]: "Australian Dollar",
  [Currency.AZM]: "Azerbaijanian Manat",
  [Currency.BSD]: "Bahamian Dollar",
  [Currency.BHD]: "Bahraini Dinar",
  [Currency.THB]: "Baht",
  [Currency.PAB]: "Balboa",
  [Currency.BBD]: "Barbados Dollar",
  [Currency.BYR]: "Belarussian Ruble",
  [Currency.BZD]: "Belize Dollar",
  [Currency.BMD]: "Bermudian Dollar",
  [Currency.VEB]: "Bolivar",
  [Currency.BOB]: "Boliviano",
  [Currency.BGN]: "Bulgarian Lev",
  [Currency.BRL]: "Brazilian Real",
  [Currency.BND]: "Brunei Dollar",
  [Currency.BIF]: "Burundi Franc",
  [Currency.CAD]: "Canadian Dollar",
  [Currency.CVE]: "Cape Verde Escudo",
  [Currency.KYD]: "Cayman Islands Dollar",
  [Currency.GHC]: "Cedi",
  [Currency.XAF]: "CFA Franc",
  [Currency.XPF]: "CFP Franc",
  [Currency.CLP]: "Chilean Peso",
  [Currency.COP]: "Colombian Peso",
  [Currency.KMF]: "Comoro Franc",
  [Currency.NIO]: "Cordoba Oro",
  [Currency.CRC]: "Costa Rican Colon",
  [Currency.CUP]: "Cuban Peso",
  [Currency.CYP]: "Cyprus Pound",
  [Currency.CZK]: "Czech Koruna",
  [Currency.DKK]: "Danish Krone",
  [Currency.GMD]: "Dalasi",
  [Currency.MKD]: "Denar",
  [Currency.AED]: "Dirham",
  [Currency.DJF]: "Djibouti Franc",
  [Currency.STD]: "Dobra",
  [Currency.DOP]: "Dominican Peso",
  [Currency.VND]: "Dong",
  [Currency.AMD]: "Dram",
  [Currency.XCD]: "East Carribean Dollar",
  [Currency.EGP]: "Egyptian Pound",
  [Currency.SVC]: "El Salvador Colon",
  [Currency.ETB]: "Ethopian Birr",
  [Currency.EUR]: "Euro",
  [Currency.FKP]: "Falkland Islands Pound",
  [Currency.FJD]: "Fiji Dollar",
  [Currency.HUF]: "Forint",
  [Currency.CDF]: "Franc Congolais",
  [Currency.GIP]: "Gibraltar Pound",
  [Currency.XAU]: "Gold",
  [Currency.HTG]: "Gourde",
  [Currency.PYG]: "Guarani",
  [Currency.GNF]: "Guinea Franc",
  [Currency.GYD]: "Guyana Dollar",
  [Currency.HKD]: "HKD",
  [Currency.UAH]: "Hryvnia",
  [Currency.ISK]: "Iceland Krona",
  [Currency.INR]: "Indian Rupee",
  [Currency.IQD]: "Iraqi Dinar",
  [Currency.IRR]: "Iranian Rial",
  [Currency.JMD]: "Jamaican Dollar",
  [Currency.JOD]: "Jordanian Dinar",
  [Currency.KES]: "Kenyan Shilling",
  [Currency.PGK]: "Kina",
  [Currency.LAK]: "Kip",
  [Currency.EEK]: "Kroon",
  [Currency.HRK]: "Kuna",
  [Currency.KWD]: "Kuwaiti Dinar",
  [Currency.MWK]: "Kwacha",
  [Currency.AOA]: "Kwanza",
  [Currency.MMK]: "Kyat",
  [Currency.GEL]: "Lari",
  [Currency.LVL]: "Latvian Lats",
  [Currency.LBP]: "Lebanese Pound",
  [Currency.ALL]: "Lek",
  [Currency.HNL]: "Lempira",
  [Currency.SLL]: "Leone",
  [Currency.ROL]: "Leu",
  [Currency.LRD]: "Liberian Dollar",
  [Currency.LYD]: "Libyan Dinar",
  [Currency.SZL]: "Lilangeni",
  [Currency.LTL]: "Lithuanian Litas",
  [Currency.LSL]: "Loti",
  [Currency.MGF]: "Malagasy Franc",
  [Currency.MYR]: "Malaysian Ringgit",
  [Currency.MTL]: "Maltese Lira",
  [Currency.TMM]: "Manat",
  [Currency.MUR]: "Mauritius Rupee",
  [Currency.MZM]: "Metical",
  [Currency.MXN]: "Mexican Peso",
  [Currency.MDL]: "Moldovan Leu",
  [Currency.MAD]: "Morrocan Dirham",
  [Currency.NGN]: "Naira",
  [Currency.ERN]: "Nakfa",
  [Currency.NAD]: "Namibia Dollar",
  [Currency.NPR]: "Nepalese Rupee",
  [Currency.ANG]: "Netherlands Antillian Guilder",
  [Currency.YUM]: "New Dinar",
  [Currency.ILS]: "New Israeli Sheqel",
  [Currency.TWD]: "New Taiwan Dollar",
  [Currency.NZD]: "New Zealand Dollar",
  [Currency.KPW]: "North Korean Won",
  [Currency.NOK]: "Norwegian Krone",
  [Currency.BTN]: "Ngultrum",
  [Currency.PEN]: "Nuevo Sol",
  [Currency.MRO]: "Ouguiya",
  [Currency.TOP]: "Pa&apos;anga",
  [Currency.PKR]: "Pakistan Rupee",
  [Currency.XPD]: "Palladium",
  [Currency.MOP]: "Pataca",
  [Currency.UYU]: "Peso Uruguayo",
  [Currency.PHP]: "Philippine Peso",
  [Currency.XPT]: "Platinum",
  [Currency.GBP]: "Pound Sterling",
  [Currency.BWP]: "Pula",
  [Currency.QAR]: "Qatari Rial",
  [Currency.GTQ]: "Quetzal",
  [Currency.ZAR]: "Rand",
  [Currency.OMR]: "Rial Omani",
  [Currency.KHR]: "Riel",
  [Currency.MVR]: "Rufiyaa",
  [Currency.RON]: "Rumen Leyi",
  [Currency.IDR]: "Rupiah",
  [Currency.RUB]: "Russian Ruble",
  [Currency.RWF]: "Rwanda Franc",
  [Currency.SAR]: "Saudi Riyal",
  [Currency.XDR]: "SDR",
  [Currency.SCR]: "Seychelles Rupee",
  [Currency.XAG]: "Silver",
  [Currency.SGD]: "Singapore Dollar",
  [Currency.SKK]: "Slovak Koruna",
  [Currency.SBD]: "Solomon Islands Dollar",
  [Currency.SOS]: "Somali Shilling",
  [Currency.LKR]: "Sri Lanka Rupee",
  [Currency.KGS]: "Som",
  [Currency.TJS]: "Somoni",
  [Currency.SHP]: "St. Helena Pound",
  [Currency.SDD]: "Sudanese Dinar",
  [Currency.SRG]: "Suriname Guilder",
  [Currency.SEK]: "Swedish Krona",
  [Currency.CHF]: "Swiss Franc",
  [Currency.SYP]: "Syrian Pound",
  [Currency.BDT]: "Taka",
  [Currency.WST]: "Tala",
  [Currency.TZS]: "Tanzanian Shilling",
  [Currency.KZT]: "Tenge",
  [Currency.SIT]: "Tolar",
  [Currency.TTD]: "Trinidad and Tobago Dollar",
  [Currency.MNT]: "Tugrik",
  [Currency.TND]: "Tunisian Dinar",
  [Currency.TRY]: "Turkish Lira",
  [Currency.UGX]: "Uganda Shilling",
  [Currency.USD]: "American Dollar",
  [Currency.UZS]: "Uzbekistan Sum",
  [Currency.VUV]: "Vatu",
  [Currency.KRW]: "Won",
  [Currency.YER]: "Yemeni Rial",
  [Currency.JPY]: "Yen",
  [Currency.CNY]: "Yuan Renminbi",
  [Currency.ZWD]: "Zimbabwe Dollar",
  [Currency.PLN]: "Zloty",
};

export function currencyCases(): Currency[] {
  return Object.values(Currency);
}

export function getCurrencyAlias(value: Currency): string {
  return aliases[value];
}
