export const Unit = {
  Gun: "DAY",
  Ay: "MON",
  Yil: "ANN",
  Saat: "HUR",
  Dk: "D61",
  Sn: "D62",
  Adet: "C62",
  Pk: "PA",
  Kutu: "BX",
  Mgm: "MGM",
  Grm: "GRM",
  Kgm: "KGM",
  Ltr: "LTR",
  Ton: "TNE",
  Nt: "NT",
  Gt: "GT",
  Mmt: "MMT",
  Cmt: "CMT",
  Mtr: "MTR",
  Ktm: "KTM",
  Mlt: "MLT",
  Mm3: "MMQ",
  Cm2: "CMK",
  Cmq: "CMQ",
  M2: "MTK",
  M3: "MTQ",
  Kjo: "KJO",
  Clt: "CLT",
  Ct: "CT",
  Kwh: "KWH",
  Mwh: "MWH",
  Cct: "CCT",
  Gkj: "D30",
  Klt: "D40",
  Lpa: "LPA",
  Kgm2: "B32",
  Ncl: "NCL",
  Pr: "PR",
  Kmt: "R9",
  Set: "SET",
  T3: "T3",
  Scm: "Q37",
  Ncm: "Q39",
  Mmbtu: "J39",
  Cm3: "G52",
  Dzn: "DZN",
  Dm2: "DMK",
  Dmt: "DMT",
  Har: "HAR",
  Lm: "LM",
} as const;

export type Unit = (typeof Unit)[keyof typeof Unit];

const unitAliases: Record<Unit, string> = {
  [Unit.Gun]: "Gün",
  [Unit.Ay]: "Ay",
  [Unit.Yil]: "Yıl",
  [Unit.Saat]: "Saat",
  [Unit.Dk]: "Dakika",
  [Unit.Sn]: "Saniye",
  [Unit.Adet]: "Adet",
  [Unit.Pk]: "Paket",
  [Unit.Kutu]: "Kutu",
  [Unit.Mgm]: "Mg",
  [Unit.Grm]: "Gram",
  [Unit.Kgm]: "Kg",
  [Unit.Ltr]: "Lt",
  [Unit.Ton]: "Ton",
  [Unit.Nt]: "Net Ton",
  [Unit.Gt]: "Gross ton",
  [Unit.Mmt]: "Mm",
  [Unit.Cmt]: "Cm",
  [Unit.Mtr]: "M",
  [Unit.Ktm]: "Km",
  [Unit.Mlt]: "Ml",
  [Unit.Mm3]: "Mm3",
  [Unit.Cm2]: "Cm2",
  [Unit.Cmq]: "Cm3",
  [Unit.M2]: "M2",
  [Unit.M3]: "M3",
  [Unit.Kjo]: "Kj",
  [Unit.Clt]: "Cl",
  [Unit.Ct]: "Karat",
  [Unit.Kwh]: "Kwh",
  [Unit.Mwh]: "Mwh",
  [Unit.Cct]: "Ton Başına Taşıma Kapasitesi",
  [Unit.Gkj]: "Brüt Kalori",
  [Unit.Klt]: "1000 Lt",
  [Unit.Lpa]: "Saf Alkol Lt",
  [Unit.Kgm2]: "Kg M2",
  [Unit.Ncl]: "Hücre Adet",
  [Unit.Pr]: "Çift",
  [Unit.Kmt]: "1000 M3",
  [Unit.Set]: "Set",
  [Unit.T3]: "1000 Adet",
  [Unit.Scm]: "Scm",
  [Unit.Ncm]: "Ncm",
  [Unit.Mmbtu]: "Mmbtu",
  [Unit.Cm3]: "Cm³",
  [Unit.Dzn]: "Düzine",
  [Unit.Dm2]: "Dm2",
  [Unit.Dmt]: "Dm",
  [Unit.Har]: "Ha",
  [Unit.Lm]: "Metretül (LM)",
};

export function unitCases(): Unit[] {
  return Object.values(Unit);
}

export function getUnitAlias(value: Unit): string {
  return unitAliases[value];
}
